name: 'Initial test'

on:
  push:
    branches:
    - tf-github-action
    - tmp
    paths:
    - .github/workflows/test-public.yml

jobs:
  job-test:
    name: Test job
    #runs-on: [dev]
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./live/test/storage_account_tags
    steps:
    - uses: actions/checkout@v4
      name: Checkout

    - name: Test shell
      run: |
        echo "GITHUB_REF_NAME = '$GITHUB_REF_NAME'"

  job-tmp:
    name: Job for 'tmp'
    if: (github.ref_name == 'tmp')
    runs-on: ubuntu-latest
    needs: [job-test]

    defaults:
      run:
        shell: bash
        working-directory: ./live/test/storage_account_tags
    steps:
    - uses: actions/checkout@v4
      name: Checkout

    - name: Test shell
      run: |
        echo "This should be branch 'tmp'"
        echo "GITHUB_REF_NAME = '$GITHUB_REF_NAME'"

  job-tf-github-action:
    name: Job for 'tf-github-action'
    if: (github.ref_name == 'tf-github-action')
    runs-on: ubuntu-latest
    needs: [job-test]

    defaults:
      run:
        shell: bash
        working-directory: ./live/test/storage_account_tags
    steps:
    - uses: actions/checkout@v4
      name: Checkout

    - name: Test shell
      run: |
        echo "This should be branch 'tf-github-action'"
        echo "GITHUB_REF_NAME = '$GITHUB_REF_NAME'"
