name: 'Resusable workflow - Terraform deploy'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      working-directory:
        required: true
        type: string

jobs:
  terraform-plan:
    name: 'Terraform Plan'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_SPN_APP_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_SPN_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}

    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ~1.9

    - name: Configure access to private GitHub repo
      run: git config --global url."https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com".insteadOf https://github.com

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate -no-color

    - name: Terraform Plan
      run: terraform plan -no-color -input=false

  terraform-apply:
    name: 'Terraform Apply'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_SPN_APP_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_SPN_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: [terraform-plan]

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}

    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ~1.9

    - name: Configure access to private GitHub repo
      run: git config --global url."https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com".insteadOf https://github.com

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false