name: 'Resusable workflow - Terraform deploy'

on:
  workflow_call:
    inputs:
      # setup-terraform requires bash
      defaults_shell:
        required: false
        type: string
        default: bash
      environment:
        required: true
        type: string
      runs_on:
        required: false
        type: string
        default: ubuntu-latest
      terraform_version:
        required: true
        type: string
      working_directory:
        required: true
        type: string

jobs:
  job-terraform-plan:
    name: 'Terraform Plan'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_SPN_APP_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_SPN_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ${{ inputs.runs_on }}
    outputs:
      terraform_plan_exitcode: ${{ steps.step-terraform-plan.outputs.exitcode }}

    defaults:
      run:
        shell: ${{ inputs.defaults_shell }}
        working-directory: ${{ inputs.working_directory }}

    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Configure access to private GitHub repo
      run: git config --global url."https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com".insteadOf https://github.com

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate -no-color

    - name: Terraform Plan
      id: step-terraform-plan
      run: |
        export exitcode=0
        terraform plan -detailed-exitcode -no-color -out tfplan || export exitcode=$?

        echo "exitcode=$exitcode" >> $GITHUB_OUTPUT

        if [ $exitcode -eq 1 ]; then
          echo "Error with Terraform Plan"
          exit 1
        else
          exit 0
        fi

  job-terraform-apply:
    name: 'Terraform Apply'
    if: needs.job-terraform-plan.outputs.terraform_plan_exitcode == 2
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_SPN_APP_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_SPN_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    runs-on: ${{ inputs.runs_on }}
    environment: ${{ inputs.environment }}
    needs: [job-terraform-plan]

    defaults:
      run:
        shell: ${{ inputs.defaults_shell }}
        working-directory: ${{ inputs.working_directory }}

    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Configure access to private GitHub repo
      run: git config --global url."https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com".insteadOf https://github.com

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false